import type { EdinburghPage } from "@/lib/edinburgh-service-content";

export type ScotlandPageSlug =
  | "aeo-agency-scotland"
  | "answer-engine-optimisation-scotland"
  | "ai-visibility-scotland"
  | "ai-systems-scotland"
  | "ai-automation-scotland"
  | "aeo-agency-oban"
  | "ai-visibility-oban"
  | "ai-systems-west-highlands"
  | "business-automation-west-highlands";

const reviewed = "1 August 2026";
const scotland = [
  { type: "Country" as const, name: "Scotland" },
  { type: "Country" as const, name: "United Kingdom" },
];
const oban = [
  { type: "City" as const, name: "Oban" },
  { type: "AdministrativeArea" as const, name: "Argyll and Bute" },
  ...scotland,
];
const westHighlands = [
  { type: "AdministrativeArea" as const, name: "West Highlands" },
  { type: "AdministrativeArea" as const, name: "Argyll and Bute" },
  ...scotland,
];

const noGuarantee = {
  question: "Can mccaigs guarantee rankings, indexing, or inclusion in AI answers?",
  answer: "No. Search and answer systems control what they crawl, index, rank, cite, or recommend. mccaigs can improve the clarity, structure, accessibility, and evidence of the source material, then report observations with their limitations.",
};

export const scotlandPages = [
  {
    slug: "aeo-agency-scotland",
    path: "/aeo-agency-scotland",
    title: "AEO Agency Scotland",
    description: "A Scotland-wide AEO agency for technical audits, structured knowledge, schema, answer-ready content, deterministic assistants, and implementation.",
    h1: "A Scotland-wide AEO agency built for technical implementation",
    eyebrow: "AEO partner / Scotland",
    kind: "service",
    definition: "mccaigs is an Edinburgh-based technical studio serving organisations across Scotland. Its AEO work connects technical SEO, clear service information, structured data, machine-readable public knowledge, evidence, and controlled assistants so people and machines can understand an organisation more accurately.",
    price: "AEO Audit from £299. Full Technical AEO Implementation from £799.",
    cta: "Discuss a Scotland-wide AEO project",
    sections: [
      { heading: "One technical source across varied Scottish markets", paragraphs: ["A Scottish organisation may serve dense urban markets, rural communities, islands, or customers distributed across several regions. Its website must state that coverage accurately without multiplying one service description into thin town pages.", "mccaigs maps real services, audiences, locations, evidence, and buyer questions to a deliberate canonical structure. The aim is a useful public source that remains coherent in conventional search, answer engines, AI-assisted research, and direct customer journeys."] },
      { heading: "Implementation beyond a marketing-led audit", paragraphs: ["An AEO audit should lead to work that can be shipped. mccaigs can implement metadata, internal links, content hierarchy, schema, public knowledge files, deterministic answers, and the underlying Next.js architecture rather than handing over a generic score.", "This suits professional services, tourism and hospitality, food and drink, education, energy and engineering, manufacturing, public bodies, and third-sector organisations that need technical delivery with clear limits."] },
    ],
    approach: ["Map services, audiences, regions, evidence, and buyer questions.", "Audit crawlability, canonicals, metadata, schema, and extractable answers.", "Assign one useful canonical route to each approved commercial intent.", "Implement visible content and matching machine-readable knowledge.", "Test routes and monitor external observations without promising outcomes."],
    deliverables: ["Scotland-wide AEO audit", "Intent and canonical route map", "Technical and content implementation", "Schema and entity clarification", "Public knowledge and llms file alignment", "Measurement and maintenance plan"],
    fit: ["Scottish SMEs and organisations with specialist services that are difficult to summarise", "Distributed teams serving more than one Scottish region", "Teams seeking implementation across websites, knowledge, and controlled assistants"],
    limitations: ["mccaigs is not a paid-media, social-management, backlink, or high-volume content agency.", "A separate local search or editorial programme may be needed when the main gap is listings, reviews, independent coverage, or sustained publication."],
    proof: [{ href: "/ai-visibility-case-study", label: "mccaigs AI visibility architecture", text: "A repository-backed example of connected pages, schema, public knowledge, sitemap coverage, and deterministic answers." }, { href: "/insights/mccaigs-tower-structured-visitor-system-case-study", label: "Structured visitor system in Oban", text: "An independent, unofficial visitor project showing structured events, multilingual content, local context, and controlled answers." }],
    related: [{ href: "/answer-engine-optimisation-scotland", label: "How AEO works across Scotland" }, { href: "/ai-visibility-scotland", label: "Assess AI visibility in Scotland" }, { href: "/aeo-agency-oban", label: "AEO support for Oban organisations" }, { href: "/seo-vs-aeo-vs-ai-visibility", label: "Compare SEO, AEO, and AI visibility" }],
    reviewed, areas: scotland,
    faqs: [{ question: "What does a Scotland-wide AEO agency do?", answer: "It improves the technical and editorial sources that help answer systems understand an organisation, including architecture, crawlability, direct answers, entities, evidence, structured data, internal links, and public knowledge." }, { question: "Is mccaigs based across Scotland?", answer: "mccaigs is based in Edinburgh and serves suitable organisations throughout Scotland. It does not claim offices in other Scottish locations." }, { question: "What does an AEO audit cost?", answer: "The approved public starting price is £299. Full Technical AEO Implementation starts from £799, with scope confirmed after discovery." }, noGuarantee],
  },
  {
    slug: "answer-engine-optimisation-scotland", path: "/answer-engine-optimisation-scotland", title: "Answer Engine Optimisation Scotland", description: "Answer Engine Optimisation for Scottish organisations, covering technical access, entities, evidence, structured knowledge, schema, and useful direct answers.", h1: "Answer Engine Optimisation for organisations across Scotland", eyebrow: "AEO explained / Scotland", kind: "service",
    definition: "Answer Engine Optimisation, or AEO, makes trustworthy public information easier for search and AI answer systems to locate, interpret, and extract. In Scotland, that often means representing services, sectors, regional coverage, evidence, and practical answers without creating duplicate pages for every place served.", price: "AEO Audit from £299. Full Technical AEO Implementation from £799.", cta: "Plan a Scottish AEO implementation",
    sections: [
      { heading: "SEO foundations with a clearer knowledge layer", paragraphs: ["AEO depends on crawlable pages, sound technical SEO, useful internal links, performance, and authority. It adds a close review of whether a machine can identify the organisation, connect its services and evidence, and extract an answer without changing the meaning.", "For Scottish organisations with mixed audiences, information may be split across websites, directories, booking platforms, PDFs, and staff knowledge. AEO begins by deciding what the owned website must state clearly and which source is authoritative."] },
      { heading: "Build for urban, rural, and island service delivery", paragraphs: ["A national page should explain what is available across Scotland. A regional page is justified only when local operating conditions, evidence, and audience questions materially change the answer. This protects users and search systems from repetitive location content.", "mccaigs implements the approved route map through visible copy, headings, metadata, schema that matches the page, public knowledge files, and tested deterministic answers."] },
    ],
    approach: ["Establish the business facts and approved service boundary.", "Map questions to canonical pages and identify duplicate intent.", "Repair technical access, hierarchy, metadata, and internal links.", "Add direct answers, evidence, and accurate structured data.", "Validate machine-readable outputs and maintain the source."],
    deliverables: ["AEO and technical SEO assessment", "Canonical intent architecture", "Answer-ready content implementation", "Schema and breadcrumb markup", "Knowledge endpoint updates", "Documented evidence and limitations"],
    fit: ["Organisations whose public information is fragmented or ambiguous", "Businesses serving several Scottish regions without a clear content hierarchy", "Teams rebuilding a website and wanting SEO and AEO designed together"],
    limitations: ["AEO cannot compensate for an unclear service, unsupported claims, or inaccessible evidence.", "Publishing more pages is not automatically useful. Some questions belong in an Insight or an existing canonical service page."],
    proof: [{ href: "/answer-engine-optimisation", label: "What is Answer Engine Optimisation?", text: "The established public introduction to AEO, structured data, and answer-ready source content." }],
    related: [{ href: "/aeo-agency-scotland", label: "Choose a technical AEO partner" }, { href: "/ai-visibility-scotland", label: "Measure AI visibility across Scotland" }, { href: "/answer-engine-optimisation-edinburgh", label: "AEO for Edinburgh organisations" }, { href: "/aeo-agency-oban", label: "Regional AEO work in Oban" }],
    reviewed, areas: scotland,
    faqs: [{ question: "What is AEO?", answer: "AEO is the work of making accurate, supported information easier for answer systems to find, understand, and extract." }, { question: "How is a Scotland page different from a location page?", answer: "A Scotland page explains national service delivery and shared needs. A regional page should exist only when local evidence, audiences, or operating conditions make its content meaningfully different." }, { question: "Does schema alone provide AEO?", answer: "No. Schema can clarify visible content but cannot replace useful pages, technical access, evidence, or consistent public information." }, noGuarantee],
  },
  {
    slug: "ai-visibility-scotland", path: "/ai-visibility-scotland", title: "AI Visibility Scotland", description: "AI visibility assessment and implementation for Scottish organisations, focused on source accuracy, entity clarity, structured knowledge, and careful monitoring.", h1: "AI visibility for Scottish organisations", eyebrow: "AI discovery / Scotland", kind: "service",
    definition: "AI visibility describes whether public sources allow AI-assisted search and research systems to discover, understand, and represent an organisation accurately. mccaigs separates dated observations from the technical work that improves owned sources.", price: "AI Visibility Management from £99 per month.", cta: "Start a Scottish AI visibility review",
    sections: [
      { heading: "Test accuracy, not vanity mentions", paragraphs: ["A useful baseline records the platform, date, prompt, response, apparent sources, and whether the organisation, services, evidence, and Scottish coverage were described accurately. Results can vary by model, account, location, and update cycle.", "The review then traces gaps back to owned pages, entity consistency, structured data, crawl access, and public knowledge. A mention with the wrong service or geography is not treated as success."] },
      { heading: "Improve the source that Scottish buyers can verify", paragraphs: ["The strongest practical work usually improves the website itself: clear sector and service information, evidence connected to claims, deliberate page relationships, direct answers, and consistent machine-readable facts.", "This matters across legal and financial services, tourism, food and drink, engineering, manufacturing, education, and third-sector organisations where accuracy and trust are more useful than speculative AI copy."] },
    ],
    approach: ["Define representative Scottish buyer and research questions.", "Record dated observations and their uncertainty.", "Audit entity, service, geography, evidence, and source consistency.", "Implement approved owned-source improvements.", "Repeat comparable checks and report change carefully."],
    deliverables: ["Dated AI visibility baseline", "Entity and source consistency review", "Prompt observation record", "Owned-source implementation plan", "Technical improvements", "Measured follow-up report"],
    fit: ["Organisations concerned about incomplete or inaccurate AI descriptions", "Teams with useful evidence that is difficult to find or connect", "Businesses wanting an evidence-led baseline before implementation"],
    limitations: ["Prompt testing is a sample, not a census of every user or platform.", "Third-party systems may update on their own schedules and may not use the improved source."],
    proof: [{ href: "/ai-visibility-case-study", label: "AI visibility case study", text: "How mccaigs connected its owned pages, schema, knowledge files, sitemap, and deterministic assistant." }],
    related: [{ href: "/aeo-agency-scotland", label: "Implement Scotland-wide AEO" }, { href: "/ai-visibility-oban", label: "AI visibility for Oban businesses" }, { href: "/seo-vs-aeo-vs-ai-visibility", label: "Choose the right discovery discipline" }],
    reviewed, areas: scotland,
    faqs: [{ question: "What is AI visibility?", answer: "It is the degree to which public sources support accurate discovery and representation in AI-assisted search and research." }, { question: "How is AI visibility measured?", answer: "mccaigs combines source and entity checks with dated prompt observations, while recording platform variation and evidence limits." }, { question: "What is the approved starting price?", answer: "AI Visibility Management starts from £99 per month. Wider implementation is scoped after discovery." }, noGuarantee],
  },
  {
    slug: "ai-systems-scotland", path: "/ai-systems-scotland", title: "AI Systems Scotland", description: "Practical AI systems for Scottish organisations, including controlled assistants, structured knowledge, portals, internal tools, and maintained workflows.", h1: "Practical AI systems for Scottish organisations", eyebrow: "Operational AI / Scotland", kind: "service",
    definition: "mccaigs designs and builds maintained AI systems for Scottish organisations: controlled assistants, structured knowledge tools, portals, internal applications, workflow orchestration, and carefully bounded generative features. The studio is based in Edinburgh and can deliver remotely across Scotland.", price: "Priced following discovery.", cta: "Discuss a practical AI system",
    sections: [
      { heading: "Design around the operation, not the model", paragraphs: ["A rural tourism organisation, an engineering firm, a professional practice, and a public body have different data, permissions, risks, and service patterns. The right system begins with those operating facts rather than a generic chatbot demonstration.", "Deterministic rules handle decisions that need predictable outcomes. AI is introduced where classification, retrieval, summarisation, or drafting adds enough value, with validation and human review where consequences matter."] },
      { heading: "Support distributed teams and limited technical capacity", paragraphs: ["Many Scottish teams work across sites or serve customers at a distance. Useful systems can bring approved knowledge, enquiries, documents, handovers, and next actions into one controlled interface without forcing a small team to maintain several fragile tools.", "Production work includes ownership, access, fallbacks, logs, maintenance, and a usable interface. The system should remain understandable after launch."] },
    ],
    approach: ["Map users, decisions, source data, and service boundaries.", "Choose rules where logic is sufficient.", "Prototype the smallest complete operational path.", "Add permissions, validation, fallbacks, and human review.", "Test, document, launch, and maintain the system."],
    deliverables: ["Deterministic assistants", "Structured knowledge systems", "Client and staff portals", "AI-assisted internal tools", "Workflow applications", "Operating and maintenance documentation"],
    fit: ["Scottish organisations with a defined operational problem", "Distributed teams that need one approved source", "Businesses moving from an experiment to a controlled application"],
    limitations: ["An off-the-shelf product may be better for a common process with no need for bespoke software.", "Open-ended automation without an approved owner, data boundary, or review process is not a suitable starting point."],
    proof: [{ href: "/insights/deterministic-assistant-vs-generative-chatbot-case-study", label: "Deterministic assistant case study", text: "A practical comparison of approved-answer retrieval and open-ended generative chat." }, { href: "/insights/mccaigs-tower-structured-visitor-system-case-study", label: "Structured visitor system", text: "Regional evidence for connected events, multilingual content, and controlled answers." }],
    related: [{ href: "/ai-automation-scotland", label: "AI-assisted workflow automation" }, { href: "/ai-systems-west-highlands", label: "AI systems for the West Highlands" }, { href: "/systems", label: "View selected technical systems" }],
    reviewed, areas: scotland,
    faqs: [{ question: "What counts as an AI system?", answer: "A useful AI system combines an interface, approved data, workflow rules, integrations, permissions, fallbacks, and operating ownership around any AI capability." }, { question: "Can systems be delivered outside Edinburgh?", answer: "Yes. mccaigs is based in Edinburgh and can deliver suitable projects remotely for organisations throughout Scotland." }, { question: "Does every system need generative AI?", answer: "No. Deterministic software is often more dependable for known rules. AI should be used only where its variability adds clear value." }, noGuarantee],
  },
  {
    slug: "ai-automation-scotland", path: "/ai-automation-scotland", title: "AI Automation Scotland", description: "AI automation for Scottish organisations, combining reliable workflow rules, structured data, validation, human review, and useful AI assistance.", h1: "AI automation for Scottish organisations with real work to improve", eyebrow: "AI-assisted workflows / Scotland", kind: "service",
    definition: "AI automation uses AI inside a defined business workflow, while deterministic rules control validation, permissions, routing, and critical decisions. mccaigs builds these systems for Scottish SMEs and organisations where the process, owner, and useful outcome are clear.", price: "Priced following discovery.", cta: "Map an AI automation opportunity",
    sections: [
      { heading: "Automate a bounded task, not an entire business", paragraphs: ["Useful starting points include classifying enquiries, retrieving approved knowledge, preparing document drafts, extracting structured fields, assembling reports, and supporting handovers. Each task needs a clear input, expected output, exception path, and accountable owner.", "For distributed Scottish teams, well-designed automation can reduce repeated administration and make status easier to see. It should not remove judgement from decisions that require professional, regulatory, safety, or customer responsibility."] },
      { heading: "Join AI to dependable workflow logic", paragraphs: ["AI can interpret or draft, while ordinary software checks required fields, applies permissions, records state, and routes exceptions. This separation makes the system easier to test and maintain than an autonomous agent with an undefined brief.", "mccaigs can connect the workflow to a website, portal, internal tool, or existing service when the integration is technically and commercially justified."] },
    ],
    approach: ["Identify repeated work and establish a measurable baseline.", "Separate deterministic decisions from interpretive tasks.", "Design inputs, approvals, exception paths, and ownership.", "Build and evaluate the smallest safe workflow.", "Launch with monitoring and documented limits."],
    deliverables: ["Workflow and opportunity map", "AI-assisted classification or extraction", "Approval and exception handling", "Portal or internal interface", "Integration and audit trail", "Evaluation and operating guide"],
    fit: ["Teams repeating document, enquiry, reporting, or knowledge tasks", "Organisations with accessible source data and a process owner", "Businesses needing remote or distributed handovers to be more consistent"],
    limitations: ["Poor source data and an undefined process should be repaired before automation.", "mccaigs does not present autonomous AI as a substitute for accountable staff or regulated judgement."],
    proof: [{ href: "/assistant", label: "Controlled assistant demonstration", text: "A live example of approved knowledge, deterministic selection, and a defined fallback." }],
    related: [{ href: "/ai-systems-scotland", label: "Build a complete AI system" }, { href: "/business-automation-west-highlands", label: "Business automation in the West Highlands" }, { href: "/ai-automation-edinburgh", label: "AI automation in Edinburgh" }],
    reviewed, areas: scotland,
    faqs: [{ question: "What can AI automation handle?", answer: "Good candidates include bounded classification, extraction, retrieval, drafting, reporting, and handover tasks with clear inputs and review rules." }, { question: "How is AI automation different from business automation?", answer: "Business automation can use fixed rules alone. AI automation adds a probabilistic capability where interpretation or drafting is useful." }, { question: "How do you keep an automated workflow controlled?", answer: "Use typed inputs, deterministic validation, permissions, human approval where needed, exception handling, logs, and an accountable owner." }, noGuarantee],
  },
  {
    slug: "aeo-agency-oban", path: "/aeo-agency-oban", title: "AEO Agency Oban", description: "Technical AEO support for Oban organisations, grounded in structured visitor information, events, multilingual content, and controlled answers.", h1: "Technical AEO support for organisations in Oban", eyebrow: "AEO partner / Oban", kind: "service",
    definition: "mccaigs is an Edinburgh-based technical studio serving suitable organisations in Oban and across Scotland. Its regional AEO experience includes an independent, unofficial McCaig's Tower visitor website with structured events, multilingual content, local context, and deterministic visitor assistance.", price: "AEO Audit from £299. Full Technical AEO Implementation from £799.", cta: "Discuss an Oban AEO project",
    sections: [
      { heading: "Make fragmented visitor and business information usable", paragraphs: ["Oban customers may move between attraction pages, accommodation listings, ferry information, event calendars, booking platforms, maps, and local directories. When the organisation's own information is vague or poorly connected, people and machines can struggle to establish the direct answer.", "AEO can clarify services, availability, location, seasonality, evidence, booking paths, and common questions in one maintained source. The work can support tourism, hospitality, marine businesses, food and drink, events, retailers, trades, and rural professional services without pretending every organisation needs the same page structure."] },
      { heading: "Regional evidence without an invented local office", paragraphs: ["The McCaig's Tower project provides genuine implementation evidence for structured visitor knowledge in Oban. It is an independent, unofficial website and does not imply ownership of, or official authority over, the landmark.", "mccaigs does not claim an Oban office. David Robertson has a personal connection to Oban and the West Highlands, while the studio operates from Edinburgh and can deliver suitable work remotely."] },
    ],
    approach: ["Map real customer and visitor questions.", "Identify authoritative owned information and third-party dependencies.", "Create a useful canonical route and evidence structure.", "Implement schema, internal links, direct answers, and approved knowledge.", "Test the live source and document external limitations."],
    deliverables: ["Oban-focused AEO audit", "Visitor or customer question map", "Structured service and location content", "Event or venue architecture where relevant", "Schema and public knowledge alignment", "Measured maintenance plan"],
    fit: ["Oban tourism, hospitality, marine, event, retail, and service organisations", "Teams relying heavily on directories or booking platforms", "Organisations with useful local knowledge but limited internal technical capacity"],
    limitations: ["mccaigs is not an official tourism body and does not claim authority over third-party visitor information.", "Local map visibility, reviews, PR, and directory management may require additional specialist work."],
    proof: [{ href: "/insights/mccaigs-tower-structured-visitor-system-case-study", label: "McCaig's Tower structured visitor system", text: "The published case study explains the independent site's event structure, multilingual architecture, local signals, and controlled answers." }],
    related: [{ href: "/aeo-agency-scotland", label: "Scotland-wide AEO implementation" }, { href: "/ai-visibility-oban", label: "AI visibility for Oban organisations" }, { href: "/ai-systems-west-highlands", label: "AI systems for the West Highlands" }],
    reviewed, areas: oban,
    faqs: [{ question: "Does mccaigs have an office in Oban?", answer: "No. mccaigs is based in Edinburgh and serves suitable Oban organisations remotely. David Robertson has a personal connection to Oban and the West Highlands." }, { question: "What Oban evidence does mccaigs have?", answer: "The published evidence is an independent, unofficial McCaig's Tower visitor website using structured events, multilingual content, local context, and deterministic assistance." }, { question: "Which Oban organisations could benefit from AEO?", answer: "Potential fits include visitor attractions, accommodation, hospitality, marine businesses, events, food and drink, retailers, trades, and rural professional services with fragmented public information." }, noGuarantee],
  },
  {
    slug: "ai-visibility-oban", path: "/ai-visibility-oban", title: "AI Visibility Oban", description: "AI visibility for Oban tourism, hospitality, marine, event, and service organisations, focused on accurate public sources and direct answers.", h1: "AI visibility for Oban businesses and visitor organisations", eyebrow: "AI discovery / Oban", kind: "service",
    definition: "AI visibility in Oban depends on whether public sources state services, location, opening or seasonal information, facilities, booking routes, evidence, and practical answers clearly enough to be represented accurately. mccaigs assesses those sources and implements owned improvements without promising third-party inclusion.", price: "AI Visibility Management from £99 per month.", cta: "Review an Oban organisation's AI visibility",
    sections: [
      { heading: "Answer the question before the directory does", paragraphs: ["Visitors and customers often begin with practical questions: what is open, where it is, whether booking is required, how transport connects, which facilities are available, and whether a service fits their needs. If only third-party platforms explain those facts, the organisation has limited control over accuracy and updates.", "A useful owned source brings durable facts and time-sensitive information into an explicit structure. That gives conventional search, answer engines, AI interfaces, and customers a clearer place to verify the answer."] },
      { heading: "Observe results with seasonal context", paragraphs: ["Oban businesses may experience strong seasonal variation. Prompt observations and source checks must therefore record the date and avoid treating one result as a permanent measure.", "mccaigs can connect findings to service pages, event records, FAQs, multilingual content, evidence, schema, and public knowledge. Monitoring remains separate from implementation and does not imply control over an external platform."] },
    ],
    approach: ["Map practical visitor and customer questions.", "Record dated AI-assisted search observations.", "Audit owned facts, entities, booking dependencies, and evidence.", "Implement clearer source content and structured relationships.", "Repeat comparable tests and report uncertainty."],
    deliverables: ["Oban AI visibility baseline", "Visitor question and source map", "Entity and location consistency review", "Owned-source improvement plan", "Structured content implementation", "Dated follow-up reporting"],
    fit: ["Tourism and hospitality teams dependent on direct practical answers", "Marine, ferry-connected, event, and visitor-facing organisations", "Businesses whose information is spread across directories and booking services"],
    limitations: ["mccaigs cannot change information owned by an unrelated booking platform, directory, or transport provider.", "An observed answer can vary by platform, model, user, location, and date."],
    proof: [{ href: "/insights/mccaigs-tower-structured-visitor-system-case-study", label: "Structured visitor information in Oban", text: "A qualitative case study with no unsupported traffic, ranking, conversion, or citation claims." }],
    related: [{ href: "/ai-visibility-scotland", label: "Scotland-wide AI visibility" }, { href: "/aeo-agency-oban", label: "Technical AEO implementation in Oban" }, { href: "/insights/what-ai-visibility-means-for-tourism-businesses-in-oban", label: "AI visibility for Oban tourism businesses" }],
    reviewed, areas: oban,
    faqs: [{ question: "What does AI visibility mean for an Oban business?", answer: "It means public sources give AI-assisted search and research systems enough accurate information to identify the business, its location, services, practical details, and evidence." }, { question: "Does mccaigs operate the McCaig's Tower landmark?", answer: "No. The project is an independent, unofficial visitor website and is not affiliated with a council, tourism body, public authority, or operator of the landmark." }, { question: "Why do third-party platforms matter?", answer: "They often hold booking, directory, review, or travel information, but an organisation still benefits from maintaining an accurate owned source that customers can verify directly." }, noGuarantee],
  },
  {
    slug: "ai-systems-west-highlands", path: "/ai-systems-west-highlands", title: "AI Systems West Highlands", description: "Practical AI and structured knowledge systems for West Highland tourism, hospitality, marine, events, and distributed organisations.", h1: "Practical AI systems for West Highland organisations", eyebrow: "Operational AI / West Highlands", kind: "service",
    definition: "mccaigs builds controlled assistants, structured knowledge, portals, internal tools, and bounded AI features for organisations in the West Highlands. The work is designed around seasonal demand, distributed teams, third-party platforms, and limited internal technical capacity.", price: "Priced following discovery.", cta: "Discuss a West Highland AI system",
    sections: [
      { heading: "Turn scattered local knowledge into an operational source", paragraphs: ["Visitor information, events, availability, transport dependencies, facilities, policies, and local guidance may live across staff knowledge, documents, calendars, websites, and booking platforms. A structured system defines which source owns each fact and how it reaches the people who need it.", "The same pattern can support accommodation, attractions, hospitality, yacht charter and sailing, food and drink, ferries and transport, rural services, and distributed organisations. The content model must follow the real operation rather than a generic tourism template."] },
      { heading: "Controlled assistance for practical questions", paragraphs: ["A deterministic assistant can answer approved questions about facilities, access, events, or service scope, then use a clear fallback when the source does not know. Generative features may help with summarisation or drafting where variability is acceptable.", "The independent McCaig's Tower project demonstrates the regional value of structured events, multilingual visitor content, local relationships, and controlled answers without claiming quantitative outcomes."] },
    ],
    approach: ["Identify users, recurring questions, and source owners.", "Model durable facts separately from changing records.", "Choose deterministic answers and bounded AI features.", "Build the public or internal interface with permissions and fallbacks.", "Test remote operation, handover, and maintenance."],
    deliverables: ["Structured visitor knowledge", "Deterministic customer assistant", "Event and venue systems", "Internal or partner portal", "Bounded AI-assisted features", "Source ownership and maintenance guide"],
    fit: ["West Highland tourism, marine, hospitality, and event organisations", "Distributed teams managing repeated questions and handovers", "Organisations with fragmented information and limited technical resources"],
    limitations: ["A system cannot make an unrelated third-party platform accurate or available.", "Safety, travel, access, and time-sensitive information need named source owners and review rules."],
    proof: [{ href: "/insights/mccaigs-tower-structured-visitor-system-case-study", label: "McCaig's Tower visitor system case study", text: "Regional production evidence for structured events, multilingual content, and deterministic assistance." }],
    related: [{ href: "/ai-systems-scotland", label: "AI systems across Scotland" }, { href: "/business-automation-west-highlands", label: "West Highland business automation" }, { href: "/ai-visibility-oban", label: "AI visibility in Oban" }],
    reviewed, areas: westHighlands,
    faqs: [{ question: "What AI systems suit West Highland organisations?", answer: "Useful examples include structured visitor knowledge, event and venue records, controlled assistants, enquiry workflows, internal portals, and bounded document or reporting tools." }, { question: "Can mccaigs work remotely with a West Highland team?", answer: "Yes. mccaigs is based in Edinburgh and can deliver suitable work remotely, with the operating team retaining ownership of approved facts and updates." }, { question: "Does every visitor assistant need generative AI?", answer: "No. Practical recurring questions are often better served by deterministic answers from approved knowledge with a clear fallback." }, noGuarantee],
  },
  {
    slug: "business-automation-west-highlands", path: "/business-automation-west-highlands", title: "Business Automation West Highlands", description: "Business automation for West Highland organisations, connecting enquiries, bookings, events, documents, approvals, and distributed team handovers.", h1: "Business automation for West Highland organisations", eyebrow: "Operational workflows / West Highlands", kind: "service",
    definition: "Business automation connects repeated work through reliable rules, data handoffs, notifications, approvals, and visible status. For West Highland organisations, that can reduce administration across seasonal enquiries, bookings, events, suppliers, documents, and distributed teams without adding unnecessary AI.", price: "Priced following discovery.", cta: "Map a West Highland workflow",
    sections: [
      { heading: "Reduce pressure when demand and staffing change", paragraphs: ["Seasonal demand can expose fragile processes. Enquiries arrive through several channels, availability sits in third-party systems, updates are repeated manually, and important context depends on one member of staff being available.", "A useful automation maps the existing process first. Fixed rules can validate a request, assign ownership, request missing information, update status, and prepare a handover. AI is optional and should be used only for an interpretive task that cannot be handled reliably by ordinary software."] },
      { heading: "Keep people responsible and information traceable", paragraphs: ["Automation should show what happened, which source was used, who approved an exception, and what the next action is. This matters for remote professional services, marine operations, hospitality, events, local retailers, trades, and organisations coordinating across sites.", "mccaigs builds within the tools and constraints that make operational sense. The result may be a focused internal application, a portal, or an integration around an existing booking or accounting platform."] },
    ],
    approach: ["Observe the current workflow and repeated effort.", "Define rules, data owners, exceptions, and permissions.", "Choose the smallest useful automation boundary.", "Build status, handoffs, notifications, and review controls.", "Test peak and failure scenarios before launch."],
    deliverables: ["Process and bottleneck map", "Enquiry and handover workflow", "Approval and notification rules", "Portal or internal dashboard", "Third-party integration where suitable", "Audit trail and operating documentation"],
    fit: ["Small teams managing seasonal enquiry or booking pressure", "Distributed organisations with repeated handovers", "Businesses relying on spreadsheets, inboxes, and disconnected tools"],
    limitations: ["Automation should not be used to conceal a broken process or unclear ownership.", "Third-party integrations depend on available APIs, permissions, service reliability, and commercial terms."],
    proof: [{ href: "/systems", label: "Selected technical systems", text: "Examples of the studio's logic-first approach to workflows, internal tools, and operational software." }],
    related: [{ href: "/ai-automation-scotland", label: "AI-assisted automation across Scotland" }, { href: "/ai-systems-west-highlands", label: "West Highland AI systems" }, { href: "/aeo-agency-oban", label: "AEO support for Oban organisations" }],
    reviewed, areas: westHighlands,
    faqs: [{ question: "What can a West Highland business automate?", answer: "Common candidates include enquiry routing, information collection, booking handoffs, event updates, document preparation, approvals, reminders, reporting, and internal status tracking." }, { question: "Is AI required for business automation?", answer: "No. Reliable rules are usually the right foundation. AI may be added for a bounded interpretive or drafting task where it provides clear value." }, { question: "Can automation connect third-party booking tools?", answer: "Sometimes. The answer depends on the platform's API, permissions, reliability, and terms. Discovery should confirm this before a solution is promised." }, noGuarantee],
  },
] as const satisfies readonly EdinburghPage[];

export const scotlandPageMap = Object.fromEntries(scotlandPages.map((page) => [page.slug, page])) as unknown as Record<ScotlandPageSlug, EdinburghPage>;
