import type { EdinburghPage } from "@/lib/edinburgh-service-content";

export type ScotlandPageSlug =
  | "aeo-agency-scotland"
  | "answer-engine-optimisation-scotland"
  | "ai-visibility-scotland"
  | "ai-systems-scotland"
  | "ai-automation-scotland"
  | "deterministic-assistants-scotland"
  | "internal-business-systems-scotland"
  | "bespoke-software-development-scottish-smes"
  | "aeo-agency-oban"
  | "ai-visibility-oban"
  | "answer-engine-optimisation-oban"
  | "ai-visibility-inverness"
  | "answer-engine-optimisation-inverness"
  | "ai-systems-west-highlands"
  | "business-automation-west-highlands";

const reviewed = "1 August 2026";
const scotland = [
  { type: "Country" as const, name: "Scotland" },
  { type: "Country" as const, name: "United Kingdom" },
];
const oban = [
  { type: "City" as const, name: "Oban" },
  { type: "AdministrativeArea" as const, name: "Argyll and Bute" },
  ...scotland,
];
const inverness = [
  { type: "City" as const, name: "Inverness" },
  { type: "AdministrativeArea" as const, name: "Highland" },
  ...scotland,
];
const westHighlands = [
  { type: "AdministrativeArea" as const, name: "West Highlands" },
  { type: "AdministrativeArea" as const, name: "Argyll and Bute" },
  ...scotland,
];

const noGuarantee = {
  question: "Can mccaigs guarantee rankings, indexing, or inclusion in AI answers?",
  answer: "No. Search and answer systems control what they crawl, index, rank, cite, or recommend. mccaigs can improve the clarity, structure, accessibility, and evidence of the source material, then report observations with their limitations.",
};

export const scotlandPages = [
  {
    slug: "aeo-agency-scotland",
    path: "/aeo-agency-scotland",
    title: "AEO Agency Scotland",
    description: "A Scotland-wide AEO agency for technical audits, structured knowledge, schema, answer-ready content, deterministic assistants, and implementation.",
    h1: "A Scotland-wide AEO agency built for technical implementation",
    eyebrow: "AEO partner / Scotland",
    kind: "service",
    definition: "mccaigs is an Edinburgh-based technical studio serving organisations across Scotland. Its AEO work connects technical SEO, clear service information, structured data, machine-readable public knowledge, evidence, and controlled assistants so people and machines can understand an organisation more accurately.",
    price: "AI Visibility and AEO Audit £299. Full Technical AEO Implementation from £799.",
    cta: "Discuss a Scotland-wide AEO project",
    sections: [
      { heading: "One technical source across varied Scottish markets", paragraphs: ["A Scottish organisation may serve dense urban markets, rural communities, islands, or customers distributed across several regions. Its website must state that coverage accurately without multiplying one service description into thin town pages.", "mccaigs maps real services, audiences, locations, evidence, and buyer questions to a deliberate canonical structure. The aim is a useful public source that remains coherent in conventional search, answer engines, AI-assisted research, and direct customer journeys."] },
      { heading: "Implementation beyond a marketing-led audit", paragraphs: ["An AEO audit should lead to work that can be shipped. mccaigs can implement metadata, internal links, content hierarchy, schema, public knowledge files, deterministic answers, and the underlying Next.js architecture rather than handing over a generic score.", "This suits professional services, tourism and hospitality, food and drink, education, energy and engineering, manufacturing, public bodies, and third-sector organisations that need technical delivery with clear limits."] },
    ],
    approach: ["Map services, audiences, regions, evidence, and buyer questions.", "Audit crawlability, canonicals, metadata, schema, and extractable answers.", "Assign one useful canonical route to each approved commercial intent.", "Implement visible content and matching machine-readable knowledge.", "Test routes and monitor external observations without promising outcomes."],
    deliverables: ["Scotland-wide AEO audit", "Intent and canonical route map", "Technical and content implementation", "Schema and entity clarification", "Public knowledge and llms file alignment", "Measurement and maintenance plan"],
    fit: ["Scottish SMEs and organisations with specialist services that are difficult to summarise", "Distributed teams serving more than one Scottish region", "Teams seeking implementation across websites, knowledge, and controlled assistants"],
    limitations: ["mccaigs is not a paid-media, social-management, backlink, or high-volume content agency.", "A separate local search or editorial programme may be needed when the main gap is listings, reviews, independent coverage, or sustained publication."],
    proof: [{ href: "/ai-visibility-case-study", label: "mccaigs AI visibility architecture", text: "A repository-backed example of connected pages, schema, public knowledge, sitemap coverage, and deterministic answers." }, { href: "/insights/mccaigs-tower-structured-visitor-system-case-study", label: "Structured visitor system in Oban", text: "An independent, unofficial visitor project showing structured events, multilingual content, local context, and controlled answers." }],
    related: [{ href: "/answer-engine-optimisation-scotland", label: "How AEO works across Scotland" }, { href: "/ai-visibility-scotland", label: "Assess AI visibility in Scotland" }, { href: "/aeo-agency-oban", label: "AEO support for Oban organisations" }, { href: "/seo-vs-aeo-vs-ai-visibility", label: "Compare SEO, AEO, and AI visibility" }],
    reviewed, areas: scotland,
    faqs: [{ question: "What does a Scotland-wide AEO agency do?", answer: "It improves the technical and editorial sources that help answer systems understand an organisation, including architecture, crawlability, direct answers, entities, evidence, structured data, internal links, and public knowledge." }, { question: "Is mccaigs based across Scotland?", answer: "mccaigs is based in Edinburgh and serves suitable organisations throughout Scotland. It does not claim offices in other Scottish locations." }, { question: "What does an AEO audit cost?", answer: "The approved public starting price is £299. Full Technical AEO Implementation starts from £799, with scope confirmed after discovery." }, noGuarantee],
  },
  {
    slug: "answer-engine-optimisation-scotland", path: "/answer-engine-optimisation-scotland", title: "Answer Engine Optimisation Scotland", description: "Answer Engine Optimisation in Scotland for clearer entities, evidence, direct answers, structured knowledge, schema, and technically accessible source content.", h1: "Answer Engine Optimisation in Scotland for organisations that need to be understood", eyebrow: "AEO implementation / Scotland", kind: "service",
    definition: "Answer Engine Optimisation, or AEO, improves the source material that Google AI experiences, Gemini, Perplexity, ChatGPT, Copilot and other answer systems may use to identify, explain, cite, or recommend an organisation. For Scottish businesses, it connects sound SEO with clear entities, useful direct answers, evidence, structured data, and an intentional regional content architecture.", price: "AI Visibility and AEO Audit £299. Full Technical AEO Implementation from £799.", cta: "Plan a Scottish AEO implementation",
    sections: [
      { heading: "AEO and conventional SEO work together", paragraphs: ["AEO depends on crawlable pages, useful internal links, performance, indexable content, and credible sources. Those are SEO foundations. It adds a close review of whether a machine can identify the organisation, connect services to evidence, extract a concise answer, and preserve the intended meaning.", "The work does not replace conventional search optimisation. It makes the same owned source more explicit for search results, AI summaries, conversational research, and customers who need a direct answer."] },
      { heading: "Why Scottish organisations need a deliberate source", paragraphs: ["Information can be split across websites, PDFs, directories, booking platforms, staff knowledge, and regional listings. AEO establishes what the owned website should state, which evidence supports it, and which source is authoritative when details change.", "This is particularly useful for professional services, tourism and hospitality, food and drink, engineering, education, manufacturing, public bodies, and third-sector organisations whose services or geographic coverage are easily oversimplified."] },
      { heading: "Build for urban, rural, and island service delivery", paragraphs: ["A Scotland page should explain national delivery. A regional page is justified only when local operating conditions, evidence, sectors, and audience questions materially change the answer. This avoids repetitive town pages and keeps one canonical route for each approved intent.", "mccaigs implements that route map through visible copy, headings, metadata, matching schema, public knowledge files, and tested deterministic answers. Edinburgh, Oban, Inverness, and West Highland pages each have a distinct purpose rather than repeating the national page."] },
      { heading: "What the audit and implementation cover", paragraphs: ["The £299 AI Visibility and AEO Audit reviews representative answer observations alongside crawl access, entity consistency, service clarity, evidence, page intent, internal links, schema, and public knowledge. It produces prioritised findings rather than a ranking promise.", "Full Technical AEO Implementation starts from £799 and can include page architecture, direct-answer copy, metadata, schema, knowledge endpoints, deterministic assistants, and verification. Ongoing management starts from £99 per month where continued observation and maintenance are useful."] },
      { heading: "A technical studio that can ship the implementation", paragraphs: ["mccaigs works as a technical studio rather than a conventional marketing agency. The focus is website and information architecture, technical SEO, structured content, schema, public knowledge, deterministic assistants, and production implementation in the existing codebase.", "The studio does not sell backlink packages, social-media management, advertising, or generic campaign retainers. Digital PR, listings, reviews, and sustained editorial production may require a complementary specialist when those are the principal gaps."] },
    ],
    approach: ["Establish the business facts and approved service boundary.", "Map questions to canonical pages and identify duplicate intent.", "Repair technical access, hierarchy, metadata, and internal links.", "Add direct answers, evidence, and accurate structured data.", "Validate machine-readable outputs and maintain the source."],
    deliverables: ["AI Visibility and AEO Audit", "Canonical intent architecture", "Answer-ready content implementation", "Organisation, service, FAQ, and breadcrumb schema where accurate", "Knowledge endpoint and llms file updates", "Documented evidence, observations, and limitations"],
    fit: ["Organisations whose public information is fragmented or ambiguous", "Businesses serving several Scottish regions without a clear content hierarchy", "Teams rebuilding a website and wanting SEO and AEO designed together"],
    limitations: ["AEO cannot compensate for an unclear service, unsupported claims, or inaccessible evidence.", "Publishing more pages is not automatically useful. Some questions belong in an Insight or an existing canonical service page."],
    proof: [{ href: "/answer-engine-optimisation", label: "What is Answer Engine Optimisation?", text: "The established public introduction to AEO, structured data, and answer-ready source content." }, { href: "/ai-visibility-case-study", label: "AI visibility architecture case study", text: "A repository-backed account of connected pages, schema, public knowledge, sitemap coverage, and deterministic answers." }],
    related: [{ href: "/aeo-agency-scotland", label: "Choose a technical AEO partner" }, { href: "/ai-visibility-scotland", label: "Measure AI visibility across Scotland" }, { href: "/answer-engine-optimisation-edinburgh", label: "AEO for Edinburgh organisations" }, { href: "/answer-engine-optimisation-oban", label: "AEO for Oban organisations" }, { href: "/answer-engine-optimisation-inverness", label: "AEO for Inverness organisations" }],
    reviewed, areas: scotland,
    faqs: [{ question: "What is Answer Engine Optimisation?", answer: "Answer Engine Optimisation makes accurate, supported information easier for search and AI answer systems to find, understand, and extract without replacing the technical foundations of SEO." }, { question: "Which answer platforms does AEO consider?", answer: "Representative reviews can consider Google AI experiences, Gemini, Perplexity, ChatGPT, Copilot, and other relevant systems. Results vary by platform, model, user, location, and date." }, { question: "How is a Scotland page different from a location page?", answer: "A Scotland page explains national service delivery and shared needs. A regional page should exist only when local evidence, audiences, or operating conditions make its content meaningfully different." }, { question: "Does schema alone provide AEO?", answer: "No. Schema can clarify visible content but cannot replace useful pages, technical access, evidence, or consistent public information." }, { question: "What does Answer Engine Optimisation cost?", answer: "The standard AI Visibility and AEO Audit is £299. Full Technical AEO Implementation starts from £799, and ongoing management starts from £99 per month where required." }, noGuarantee],
  },
  {
    slug: "ai-visibility-scotland", path: "/ai-visibility-scotland", title: "AI Visibility Scotland", description: "AI visibility assessment and implementation for Scottish organisations, focused on source accuracy, entity clarity, structured knowledge, and careful monitoring.", h1: "AI visibility for Scottish organisations", eyebrow: "AI discovery / Scotland", kind: "service",
    definition: "AI visibility describes whether public sources allow AI-assisted search and research systems to discover, understand, and represent an organisation accurately. mccaigs separates dated observations from the technical work that improves owned sources.", price: "AI Visibility and AEO Audit £299. AI Visibility Management from £99 per month.", offerId: "introductory-ai-visibility-audit", cta: "Start a Scottish AI visibility review",
    sections: [
      { heading: "Test accuracy, not vanity mentions", paragraphs: ["A useful baseline records the platform, date, prompt, response, apparent sources, and whether the organisation, services, evidence, and Scottish coverage were described accurately. Results can vary by model, account, location, and update cycle.", "The review then traces gaps back to owned pages, entity consistency, structured data, crawl access, and public knowledge. A mention with the wrong service or geography is not treated as success."] },
      { heading: "Improve the source that Scottish buyers can verify", paragraphs: ["The strongest practical work usually improves the website itself: clear sector and service information, evidence connected to claims, deliberate page relationships, direct answers, and consistent machine-readable facts.", "This matters across legal and financial services, tourism, food and drink, engineering, manufacturing, education, and third-sector organisations where accuracy and trust are more useful than speculative AI copy."] },
    ],
    approach: ["Define representative Scottish buyer and research questions.", "Record dated observations and their uncertainty.", "Audit entity, service, geography, evidence, and source consistency.", "Implement approved owned-source improvements.", "Repeat comparable checks and report change carefully."],
    deliverables: ["Dated AI visibility baseline", "Entity and source consistency review", "Prompt observation record", "Owned-source implementation plan", "Technical improvements", "Measured follow-up report"],
    fit: ["Organisations concerned about incomplete or inaccurate AI descriptions", "Teams with useful evidence that is difficult to find or connect", "Businesses wanting an evidence-led baseline before implementation"],
    limitations: ["Prompt testing is a sample, not a census of every user or platform.", "Third-party systems may update on their own schedules and may not use the improved source."],
    proof: [{ href: "/ai-visibility-case-study", label: "AI visibility case study", text: "How mccaigs connected its owned pages, schema, knowledge files, sitemap, and deterministic assistant." }],
    related: [{ href: "/answer-engine-optimisation-scotland", label: "Implement Answer Engine Optimisation in Scotland" }, { href: "/ai-visibility-oban", label: "AI visibility for Oban businesses" }, { href: "/ai-visibility-inverness", label: "AI visibility for Inverness businesses" }, { href: "/seo-vs-aeo-vs-ai-visibility", label: "Choose the right discovery discipline" }],
    reviewed, areas: scotland,
    faqs: [{ question: "What is AI visibility?", answer: "It is the degree to which public sources support accurate discovery and representation in AI-assisted search and research." }, { question: "How is AI visibility measured?", answer: "mccaigs combines source and entity checks with dated prompt observations, while recording platform variation and evidence limits." }, { question: "What does an AI visibility review cost?", answer: "A limited introductory AI Visibility Audit is £99. The standard combined AI Visibility and AEO Audit is £299, and ongoing management starts from £99 per month." }, noGuarantee],
  },
  {
    slug: "ai-systems-scotland", path: "/ai-systems-scotland", title: "AI Systems Scotland", description: "Practical AI systems for Scottish organisations, including controlled assistants, structured knowledge, portals, internal tools, and maintained workflows.", h1: "Practical AI systems for Scottish organisations", eyebrow: "Operational AI / Scotland", kind: "service",
    definition: "mccaigs designs and builds maintained AI systems for Scottish organisations: controlled assistants, structured knowledge tools, portals, internal applications, workflow orchestration, and carefully bounded generative features. The studio is based in Edinburgh and can deliver remotely across Scotland.", price: "Priced following discovery.", cta: "Discuss a practical AI system",
    sections: [
      { heading: "Design around the operation, not the model", paragraphs: ["A rural tourism organisation, an engineering firm, a professional practice, and a public body have different data, permissions, risks, and service patterns. The right system begins with those operating facts rather than a generic chatbot demonstration.", "Deterministic rules handle decisions that need predictable outcomes. AI is introduced where classification, retrieval, summarisation, or drafting adds enough value, with validation and human review where consequences matter."] },
      { heading: "Support distributed teams and limited technical capacity", paragraphs: ["Many Scottish teams work across sites or serve customers at a distance. Useful systems can bring approved knowledge, enquiries, documents, handovers, and next actions into one controlled interface without forcing a small team to maintain several fragile tools.", "Production work includes ownership, access, fallbacks, logs, maintenance, and a usable interface. The system should remain understandable after launch."] },
    ],
    approach: ["Map users, decisions, source data, and service boundaries.", "Choose rules where logic is sufficient.", "Prototype the smallest complete operational path.", "Add permissions, validation, fallbacks, and human review.", "Test, document, launch, and maintain the system."],
    deliverables: ["Deterministic assistants", "Structured knowledge systems", "Client and staff portals", "AI-assisted internal tools", "Workflow applications", "Operating and maintenance documentation"],
    fit: ["Scottish organisations with a defined operational problem", "Distributed teams that need one approved source", "Businesses moving from an experiment to a controlled application"],
    limitations: ["An off-the-shelf product may be better for a common process with no need for bespoke software.", "Open-ended automation without an approved owner, data boundary, or review process is not a suitable starting point."],
    proof: [{ href: "/insights/deterministic-assistant-vs-generative-chatbot-case-study", label: "Deterministic assistant case study", text: "A practical comparison of approved-answer retrieval and open-ended generative chat." }, { href: "/insights/mccaigs-tower-structured-visitor-system-case-study", label: "Structured visitor system", text: "Regional evidence for connected events, multilingual content, and controlled answers." }],
    related: [{ href: "/ai-automation-scotland", label: "AI-assisted workflow automation" }, { href: "/ai-systems-west-highlands", label: "AI systems for the West Highlands" }, { href: "/systems", label: "View selected technical systems" }],
    reviewed, areas: scotland,
    faqs: [{ question: "What counts as an AI system?", answer: "A useful AI system combines an interface, approved data, workflow rules, integrations, permissions, fallbacks, and operating ownership around any AI capability." }, { question: "Can systems be delivered outside Edinburgh?", answer: "Yes. mccaigs is based in Edinburgh and can deliver suitable projects remotely for organisations throughout Scotland." }, { question: "Does every system need generative AI?", answer: "No. Deterministic software is often more dependable for known rules. AI should be used only where its variability adds clear value." }, noGuarantee],
  },
  {
    slug: "ai-automation-scotland", path: "/ai-automation-scotland", title: "AI Automation Scotland", description: "AI automation for Scottish organisations, combining reliable workflow rules, structured data, validation, human review, and useful AI assistance.", h1: "AI automation for Scottish organisations with real work to improve", eyebrow: "AI-assisted workflows / Scotland", kind: "service",
    definition: "AI automation uses AI inside a defined business workflow, while deterministic rules control validation, permissions, routing, and critical decisions. mccaigs builds these systems for Scottish SMEs and organisations where the process, owner, and useful outcome are clear.", price: "Priced following discovery.", cta: "Map an AI automation opportunity",
    sections: [
      { heading: "Automate a bounded task, not an entire business", paragraphs: ["Useful starting points include classifying enquiries, retrieving approved knowledge, preparing document drafts, extracting structured fields, assembling reports, and supporting handovers. Each task needs a clear input, expected output, exception path, and accountable owner.", "For distributed Scottish teams, well-designed automation can reduce repeated administration and make status easier to see. It should not remove judgement from decisions that require professional, regulatory, safety, or customer responsibility."] },
      { heading: "Join AI to dependable workflow logic", paragraphs: ["AI can interpret or draft, while ordinary software checks required fields, applies permissions, records state, and routes exceptions. This separation makes the system easier to test and maintain than an autonomous agent with an undefined brief.", "mccaigs can connect the workflow to a website, portal, internal tool, or existing service when the integration is technically and commercially justified."] },
    ],
    approach: ["Identify repeated work and establish a measurable baseline.", "Separate deterministic decisions from interpretive tasks.", "Design inputs, approvals, exception paths, and ownership.", "Build and evaluate the smallest safe workflow.", "Launch with monitoring and documented limits."],
    deliverables: ["Workflow and opportunity map", "AI-assisted classification or extraction", "Approval and exception handling", "Portal or internal interface", "Integration and audit trail", "Evaluation and operating guide"],
    fit: ["Teams repeating document, enquiry, reporting, or knowledge tasks", "Organisations with accessible source data and a process owner", "Businesses needing remote or distributed handovers to be more consistent"],
    limitations: ["Poor source data and an undefined process should be repaired before automation.", "mccaigs does not present autonomous AI as a substitute for accountable staff or regulated judgement."],
    proof: [{ href: "/assistant", label: "Controlled assistant demonstration", text: "A live example of approved knowledge, deterministic selection, and a defined fallback." }],
    related: [{ href: "/ai-systems-scotland", label: "Build a complete AI system" }, { href: "/business-automation-west-highlands", label: "Business automation in the West Highlands" }, { href: "/ai-automation-edinburgh", label: "AI automation in Edinburgh" }],
    reviewed, areas: scotland,
    faqs: [{ question: "What can AI automation handle?", answer: "Good candidates include bounded classification, extraction, retrieval, drafting, reporting, and handover tasks with clear inputs and review rules." }, { question: "How is AI automation different from business automation?", answer: "Business automation can use fixed rules alone. AI automation adds a probabilistic capability where interpretation or drafting is useful." }, { question: "How do you keep an automated workflow controlled?", answer: "Use typed inputs, deterministic validation, permissions, human approval where needed, exception handling, logs, and an accountable owner." }, noGuarantee],
  },
  {
    slug: "aeo-agency-oban", path: "/aeo-agency-oban", title: "AEO Agency Oban", description: "Technical AEO support for Oban organisations, grounded in structured visitor information, events, multilingual content, and controlled answers.", h1: "Technical AEO support for organisations in Oban", eyebrow: "AEO partner / Oban", kind: "service",
    definition: "mccaigs is an Edinburgh-based technical studio serving suitable organisations in Oban and across Scotland. Its regional AEO experience includes an independent, unofficial McCaig's Tower visitor website with structured events, multilingual content, local context, and deterministic visitor assistance.", price: "AI Visibility and AEO Audit £299. Full Technical AEO Implementation from £799.", cta: "Discuss an Oban AEO project",
    sections: [
      { heading: "Make fragmented visitor and business information usable", paragraphs: ["Oban customers may move between attraction pages, accommodation listings, ferry information, event calendars, booking platforms, maps, and local directories. When the organisation's own information is vague or poorly connected, people and machines can struggle to establish the direct answer.", "AEO can clarify services, availability, location, seasonality, evidence, booking paths, and common questions in one maintained source. The work can support tourism, hospitality, marine businesses, food and drink, events, retailers, trades, and rural professional services without pretending every organisation needs the same page structure."] },
      { heading: "Regional evidence without an invented local office", paragraphs: ["The McCaig's Tower project provides genuine implementation evidence for structured visitor knowledge in Oban. It is an independent, unofficial website and does not imply ownership of, or official authority over, the landmark.", "mccaigs does not claim an Oban office. David Robertson has a personal connection to Oban and the West Highlands, while the studio operates from Edinburgh and can deliver suitable work remotely."] },
    ],
    approach: ["Map real customer and visitor questions.", "Identify authoritative owned information and third-party dependencies.", "Create a useful canonical route and evidence structure.", "Implement schema, internal links, direct answers, and approved knowledge.", "Test the live source and document external limitations."],
    deliverables: ["Oban-focused AEO audit", "Visitor or customer question map", "Structured service and location content", "Event or venue architecture where relevant", "Schema and public knowledge alignment", "Measured maintenance plan"],
    fit: ["Oban tourism, hospitality, marine, event, retail, and service organisations", "Teams relying heavily on directories or booking platforms", "Organisations with useful local knowledge but limited internal technical capacity"],
    limitations: ["mccaigs is not an official tourism body and does not claim authority over third-party visitor information.", "Local map visibility, reviews, PR, and directory management may require additional specialist work."],
    proof: [{ href: "/insights/mccaigs-tower-structured-visitor-system-case-study", label: "McCaig's Tower structured visitor system", text: "The published case study explains the independent site's event structure, multilingual architecture, local signals, and controlled answers." }],
    related: [{ href: "/aeo-agency-scotland", label: "Scotland-wide AEO implementation" }, { href: "/ai-visibility-oban", label: "AI visibility for Oban organisations" }, { href: "/ai-systems-west-highlands", label: "AI systems for the West Highlands" }],
    reviewed, areas: oban,
    faqs: [{ question: "Does mccaigs have an office in Oban?", answer: "No. mccaigs is based in Edinburgh and serves suitable Oban organisations remotely. David Robertson has a personal connection to Oban and the West Highlands." }, { question: "What Oban evidence does mccaigs have?", answer: "The published evidence is an independent, unofficial McCaig's Tower visitor website using structured events, multilingual content, local context, and deterministic assistance." }, { question: "Which Oban organisations could benefit from AEO?", answer: "Potential fits include visitor attractions, accommodation, hospitality, marine businesses, events, food and drink, retailers, trades, and rural professional services with fragmented public information." }, noGuarantee],
  },
  {
    slug: "ai-visibility-oban", path: "/ai-visibility-oban", title: "AI Visibility Oban", description: "AI visibility for Oban tourism, hospitality, marine, event, and service organisations, focused on accurate public sources and direct answers.", h1: "AI visibility for Oban businesses and visitor organisations", eyebrow: "AI discovery / Oban", kind: "service",
    definition: "AI visibility in Oban depends on whether public sources state services, location, opening or seasonal information, facilities, booking routes, evidence, and practical answers clearly enough to be represented accurately. mccaigs assesses those sources and implements owned improvements without promising third-party inclusion.", price: "AI Visibility and AEO Audit £299. AI Visibility Management from £99 per month.", offerId: "introductory-ai-visibility-audit", cta: "Review an Oban organisation's AI visibility",
    sections: [
      { heading: "Answer the question before the directory does", paragraphs: ["Visitors and customers often begin with practical questions: what is open, where it is, whether booking is required, how transport connects, which facilities are available, and whether a service fits their needs. If only third-party platforms explain those facts, the organisation has limited control over accuracy and updates.", "A useful owned source brings durable facts and time-sensitive information into an explicit structure. That gives conventional search, answer engines, AI interfaces, and customers a clearer place to verify the answer."] },
      { heading: "Observe results with seasonal context", paragraphs: ["Oban businesses may experience strong seasonal variation. Prompt observations and source checks must therefore record the date and avoid treating one result as a permanent measure.", "mccaigs can connect findings to service pages, event records, FAQs, multilingual content, evidence, schema, and public knowledge. Monitoring remains separate from implementation and does not imply control over an external platform."] },
    ],
    approach: ["Map practical visitor and customer questions.", "Record dated AI-assisted search observations.", "Audit owned facts, entities, booking dependencies, and evidence.", "Implement clearer source content and structured relationships.", "Repeat comparable tests and report uncertainty."],
    deliverables: ["Oban AI visibility baseline", "Visitor question and source map", "Entity and location consistency review", "Owned-source improvement plan", "Structured content implementation", "Dated follow-up reporting"],
    fit: ["Tourism and hospitality teams dependent on direct practical answers", "Marine, ferry-connected, event, and visitor-facing organisations", "Businesses whose information is spread across directories and booking services"],
    limitations: ["mccaigs cannot change information owned by an unrelated booking platform, directory, or transport provider.", "An observed answer can vary by platform, model, user, location, and date."],
    proof: [{ href: "/insights/mccaigs-tower-structured-visitor-system-case-study", label: "Structured visitor information in Oban", text: "A qualitative case study with no unsupported traffic, ranking, conversion, or citation claims." }],
    related: [{ href: "/ai-visibility-scotland", label: "Scotland-wide AI visibility" }, { href: "/answer-engine-optimisation-oban", label: "Technical AEO implementation in Oban" }, { href: "/insights/what-ai-visibility-means-for-tourism-businesses-in-oban", label: "AI visibility for Oban tourism businesses" }],
    reviewed, areas: oban,
    faqs: [{ question: "What does AI visibility mean for an Oban business?", answer: "It means public sources give AI-assisted search and research systems enough accurate information to identify the business, its location, services, practical details, and evidence." }, { question: "Does mccaigs operate the McCaig's Tower landmark?", answer: "No. The project is an independent, unofficial visitor website and is not affiliated with a council, tourism body, public authority, or operator of the landmark." }, { question: "Why do third-party platforms matter?", answer: "They often hold booking, directory, review, or travel information, but an organisation still benefits from maintaining an accurate owned source that customers can verify directly." }, noGuarantee],
  },
  {
    slug: "answer-engine-optimisation-oban", path: "/answer-engine-optimisation-oban", title: "Answer Engine Optimisation Oban", description: "Answer Engine Optimisation for Oban organisations, connecting visitor questions, service facts, evidence, technical access, schema, and local knowledge.", h1: "Answer Engine Optimisation for Oban organisations", eyebrow: "AEO implementation / Oban", kind: "service",
    definition: "Answer Engine Optimisation in Oban makes accurate business, service, location, visitor, and practical information easier for search and AI answer systems to find and interpret. mccaigs builds the owned technical source for this work from Edinburgh, with no claim of an Oban office or control over third-party answers.", price: "AI Visibility and AEO Audit £299. Full Technical AEO Implementation from £799.", cta: "Plan an Oban AEO implementation",
    sections: [
      { heading: "Give practical local questions a verifiable source", paragraphs: ["Oban customers and visitors often need direct answers about opening, seasonality, facilities, booking, access, marine connections, events, service areas, and what happens when plans change. Those facts may be scattered across a website, social profile, directory, booking platform, and staff knowledge.", "AEO establishes which owned page answers each important question, connects the answer to supporting evidence, and keeps changing information separate from durable facts. The result is useful to people first and easier for answer systems to extract without guessing."] },
      { heading: "Local relevance without repetitive location copy", paragraphs: ["An Oban page should contain Oban-specific operating context, sectors, evidence, and questions. It should not repeat a Scotland page with a town name substituted. mccaigs maps the canonical route before writing so the local service page, national service page, and relevant Insight each have a clear role.", "Implementation can cover crawl paths, metadata, page structure, direct answers, internal links, schema that matches visible content, public knowledge, llms files, and deterministic answers. Search rankings, indexing, citations, and AI recommendations remain decisions made by external systems."] },
    ],
    approach: ["Map Oban-specific audiences, services, practical questions, and source owners.", "Audit crawl access, page intent, entities, evidence, schema, and extractable answers.", "Separate durable facts from seasonal and third-party information.", "Implement visible content and matching machine-readable knowledge.", "Verify the owned source and document external dependencies."],
    deliverables: ["Oban AI Visibility and AEO Audit", "Canonical question and page map", "Answer-ready service and visitor content", "Technical metadata and internal linking", "Accurate service, FAQ, and breadcrumb schema", "Public knowledge and validation record"],
    fit: ["Tourism, hospitality, accommodation, marine, event, food and drink, retail, trade, and professional organisations", "Teams dependent on booking platforms or directories for important facts", "Businesses with useful local expertise that is difficult to find on their owned website"],
    limitations: ["mccaigs is based in Edinburgh and does not claim an office in Oban.", "Local listings, reviews, public relations, and third-party booking content may need separate work or access."],
    proof: [{ href: "/insights/mccaigs-tower-structured-visitor-system-case-study", label: "Structured visitor system in Oban", text: "An independent, unofficial visitor project demonstrating structured events, multilingual content, local context, and controlled answers without unsupported outcome claims." }],
    related: [{ href: "/ai-visibility-oban", label: "Assess AI visibility in Oban" }, { href: "/aeo-agency-oban", label: "Choose an Oban AEO partner" }, { href: "/answer-engine-optimisation-scotland", label: "AEO across Scotland" }, { href: "/insights/how-west-highland-businesses-can-prepare-for-answer-engine-search", label: "Prepare for answer-engine search" }],
    reviewed, areas: oban,
    faqs: [{ question: "What does Answer Engine Optimisation mean for an Oban business?", answer: "It means improving the owned source so practical local, service, and visitor information is clear, supported, technically accessible, and easier for answer systems to interpret." }, { question: "How is this different from AI visibility in Oban?", answer: "AI visibility work records and diagnoses how an organisation is represented. AEO implementation changes the owned pages, structure, schema, knowledge, and internal links that can improve the source." }, { question: "What does an Oban AEO audit cost?", answer: "The standard combined AI Visibility and AEO Audit is £299. Full Technical AEO Implementation starts from £799 after scope is confirmed." }, noGuarantee],
  },
  {
    slug: "ai-visibility-inverness", path: "/ai-visibility-inverness", title: "AI Visibility Inverness", description: "AI visibility audits for Inverness organisations, covering entities, services, Highland coverage, evidence, public sources, and dated answer observations.", h1: "AI visibility for Inverness organisations", eyebrow: "AI discovery / Inverness", kind: "service",
    definition: "AI visibility in Inverness describes whether public sources allow AI-assisted search and research systems to identify an organisation, understand its services and Highland coverage, and represent it accurately. mccaigs measures representative observations and source gaps separately from the work of implementing AEO improvements.", price: "AI Visibility and AEO Audit £299. AI Visibility Management from £99 per month.", offerId: "introductory-ai-visibility-audit", cta: "Review an Inverness organisation's AI visibility",
    sections: [
      { heading: "Measure service and Highland context, not mentions alone", paragraphs: ["A useful baseline asks whether the organisation is identified correctly, whether its Inverness base or service area is accurate, whether its specialist services are understood, and which sources appear to support the answer. A bare mention or inaccurate summary is not treated as successful visibility.", "Checks record the platform, date, prompt, response, apparent sources, and uncertainty. Results can vary by model, account, location, and update cycle, so the review is a representative sample rather than a universal ranking report."] },
      { heading: "Trace gaps back to sources the organisation controls", paragraphs: ["Inverness organisations may serve the city, the wider Highlands, islands, or customers throughout Scotland. Confusing those boundaries can produce inaccurate answers. The review checks owned pages, organisation facts, service descriptions, evidence, internal links, structured data, and public knowledge for ambiguity.", "This can suit tourism and hospitality, professional services, food and drink, engineering, energy, education, rural services, charities, and distributed teams. Implementation is scoped separately so the measurement remains transparent."] },
    ],
    approach: ["Define representative buyer and research questions for Inverness and Highland markets.", "Record dated observations across relevant answer experiences.", "Review entity, service, geography, evidence, and source consistency.", "Prioritise owned-source gaps without presenting samples as universal results.", "Repeat comparable checks only where ongoing management is useful."],
    deliverables: ["Dated Inverness AI visibility baseline", "Entity and Highland coverage review", "Representative prompt observation record", "Small competitor source sample", "Prioritised owned-source findings", "Implementation or management scope where requested"],
    fit: ["Inverness organisations concerned about inaccurate or incomplete AI descriptions", "Businesses serving Highland markets with complex geographic coverage", "Teams wanting evidence before commissioning AEO implementation"],
    limitations: ["mccaigs is based in Edinburgh and does not claim an Inverness office.", "Prompt observations cannot prove what every user will see or when an external platform will update."],
    proof: [{ href: "/ai-visibility-case-study", label: "AI visibility architecture case study", text: "A verifiable account of connected owned pages, schema, public knowledge, sitemap coverage, and deterministic answers." }],
    related: [{ href: "/answer-engine-optimisation-inverness", label: "Implement AEO in Inverness" }, { href: "/ai-visibility-scotland", label: "AI visibility across Scotland" }, { href: "/insights/seo-aeo-and-ai-visibility-outside-scotlands-central-belt", label: "Discovery outside the central belt" }, { href: "/insights/why-rural-scottish-businesses-need-structured-digital-knowledge", label: "Structured knowledge for rural organisations" }],
    reviewed, areas: inverness,
    faqs: [{ question: "What is AI visibility for an Inverness organisation?", answer: "It is the degree to which public sources support accurate discovery and representation of the organisation, its services, evidence, Inverness context, and wider service area in AI-assisted search and research." }, { question: "Does mccaigs have an Inverness office?", answer: "No. mccaigs is based in Edinburgh and can serve suitable Inverness and Highland organisations remotely." }, { question: "What does an AI visibility review cost?", answer: "A limited introductory AI Visibility Audit is £99. The standard combined AI Visibility and AEO Audit is £299, and ongoing management starts from £99 per month." }, noGuarantee],
  },
  {
    slug: "answer-engine-optimisation-inverness", path: "/answer-engine-optimisation-inverness", title: "Answer Engine Optimisation Inverness", description: "Answer Engine Optimisation for Inverness organisations, connecting technical SEO, Highland coverage, evidence, direct answers, schema, and knowledge.", h1: "Answer Engine Optimisation for Inverness organisations", eyebrow: "AEO implementation / Inverness", kind: "service",
    definition: "Answer Engine Optimisation in Inverness improves the owned source that search and AI answer systems may use to understand an organisation. It combines technical SEO, clear services and geographic coverage, direct answers, evidence, structured data, and a deliberate content architecture without promising external inclusion.", price: "AI Visibility and AEO Audit £299. Full Technical AEO Implementation from £799.", cta: "Plan an Inverness AEO implementation",
    sections: [
      { heading: "Explain city, Highland, and Scotland-wide delivery accurately", paragraphs: ["An Inverness organisation may serve the city, communities across the Highlands, islands, or a national market. The owned website should state those boundaries accurately and connect each service to real operating evidence rather than producing a near-identical page for every location.", "mccaigs assigns one canonical route to each meaningful intent. Regional pages are used where local sectors, logistics, questions, or evidence change the answer; the Scotland page remains the source for national delivery."] },
      { heading: "Implement a source answer systems can parse", paragraphs: ["Technical access and conventional SEO remain essential. AEO adds direct definitions, clear entity relationships, supporting evidence, consistent organisation facts, structured data that matches visible content, public knowledge, and internal links that explain how pages relate.", "The work can support professional services, tourism and hospitality, food and drink, engineering, energy, education, charities, and rural service organisations. External systems still decide what they crawl, index, cite, rank, or recommend."] },
    ],
    approach: ["Confirm services, audiences, Highland coverage, and approved evidence.", "Map questions to canonical national, regional, service, and editorial routes.", "Audit crawlability, metadata, hierarchy, schema, and direct answers.", "Implement visible content and matching machine-readable facts.", "Validate the owned source and document limitations."],
    deliverables: ["Inverness AI Visibility and AEO Audit", "Regional intent and canonical map", "Answer-ready service content", "Technical SEO and internal-link implementation", "Accurate structured data and public knowledge", "Verification and maintenance guidance"],
    fit: ["Inverness and Highland organisations with specialist services or complex coverage", "Teams whose evidence is fragmented across pages, PDFs, directories, or staff knowledge", "Businesses rebuilding a site and wanting SEO and AEO designed together"],
    limitations: ["mccaigs does not claim an office or local listing in Inverness.", "Independent coverage, reviews, directory management, or sustained editorial work may require other specialists."],
    proof: [{ href: "/answer-engine-optimisation", label: "Answer Engine Optimisation explained", text: "The established mccaigs explanation of technical SEO, entity clarity, structured data, public knowledge, and controlled answers." }],
    related: [{ href: "/ai-visibility-inverness", label: "Assess AI visibility in Inverness" }, { href: "/answer-engine-optimisation-scotland", label: "AEO across Scotland" }, { href: "/ai-systems-west-highlands", label: "AI systems for Highland operations" }, { href: "/insights/seo-aeo-and-ai-visibility-outside-scotlands-central-belt", label: "SEO, AEO, and visibility outside the central belt" }],
    reviewed, areas: inverness,
    faqs: [{ question: "How does AEO help an Inverness business?", answer: "It makes services, locations, evidence, and direct answers clearer and technically accessible across the organisation's owned pages and machine-readable knowledge." }, { question: "Is an Inverness page always needed?", answer: "No. A dedicated page is useful only when Inverness or Highland audiences, operating conditions, questions, or evidence make the content meaningfully different from the Scotland page." }, { question: "What does Inverness AEO cost?", answer: "The standard combined AI Visibility and AEO Audit is £299. Full Technical AEO Implementation starts from £799 after discovery." }, noGuarantee],
  },
  {
    slug: "deterministic-assistants-scotland", path: "/deterministic-assistants-scotland", title: "Deterministic Assistants Scotland", description: "Deterministic assistants for Scottish organisations using approved knowledge, explicit rules, source links, controlled fallbacks, and answer ownership.", h1: "Deterministic assistants for Scottish organisations", eyebrow: "Controlled answers / Scotland", kind: "service",
    definition: "A deterministic assistant selects from approved answers and explicit rules instead of generating an open-ended response each time. mccaigs builds these controlled assistants for Scottish organisations that need predictable service information, transparent fallbacks, source ownership, and a maintainable interface.", price: "Priced following discovery.", cta: "Discuss a deterministic assistant",
    sections: [
      { heading: "Use approved answers where consistency matters", paragraphs: ["Many customer and staff questions are known in advance: service scope, facilities, process, eligibility, booking routes, project facts, and next steps. A deterministic assistant can map those questions to reviewed knowledge, return a consistent answer, link to the public source, and decline cleanly when no approved answer exists.", "This is different from a generative chatbot that composes a new response probabilistically. Generative features can still be added for a bounded task, but they should not replace approved rules where the organisation needs predictable wording or clear accountability."] },
      { heading: "Build the knowledge and operating model together", paragraphs: ["The interface is only one part of the system. A production assistant also needs named source owners, review dates, intent matching, synonyms, fallbacks, contact handoff, logging that respects privacy, and a process for updating knowledge when the service changes.", "mccaigs can connect the same approved source to website answers, internal tools, public knowledge endpoints, and staff workflows. The system remains explicit about what it knows, what it does not know, and where a person must take over."] },
    ],
    approach: ["Map recurring questions, approved answers, and accountable source owners.", "Define intent phrases, rules, confidence thresholds, and safe fallbacks.", "Build the smallest complete assistant with source links and contact handoff.", "Test known, ambiguous, unsupported, and adversarial questions.", "Document review, maintenance, privacy, and escalation."],
    deliverables: ["Approved knowledge model", "Deterministic intent and answer rules", "Branded web assistant", "Source links and fallback behaviour", "Contact or staff escalation path", "Testing and maintenance documentation"],
    fit: ["Customer-facing teams with repeated practical questions", "Staff who need one approved source across locations or services", "Organisations where consistency and explainability matter more than open-ended conversation"],
    limitations: ["A deterministic assistant cannot answer beyond its approved knowledge and should say so clearly.", "It is not a substitute for professional judgement, emergency information, or an accountable member of staff."],
    proof: [{ href: "/assistant", label: "Controlled assistant demonstration", text: "The live mccaigs assistant uses approved knowledge, deterministic selection, source links, and a defined fallback." }, { href: "/insights/deterministic-assistant-vs-generative-chatbot-case-study", label: "Deterministic assistant case study", text: "A qualitative comparison of controlled retrieval and open-ended generative chat." }],
    related: [{ href: "/ai-systems-scotland", label: "Build a wider AI system" }, { href: "/internal-business-systems-scotland", label: "Connect an internal business system" }, { href: "/ai-automation-scotland", label: "Automate a bounded workflow" }, { href: "/insights/deterministic-ai-for-ordinary-businesses", label: "Deterministic AI for ordinary businesses" }],
    reviewed, areas: scotland,
    faqs: [{ question: "What is a deterministic assistant?", answer: "It is an assistant that selects from approved knowledge and explicit rules, with controlled fallbacks, rather than generating a new open-ended answer for every question." }, { question: "Is a deterministic assistant AI?", answer: "It can use language matching or other AI-assisted components, but its answer boundary remains controlled by approved knowledge and rules." }, { question: "Can it hand a question to a person?", answer: "Yes. A clear contact or staff escalation path is part of the design when the knowledge does not contain an approved answer." }, noGuarantee],
  },
  {
    slug: "internal-business-systems-scotland", path: "/internal-business-systems-scotland", title: "Internal Business Systems Scotland", description: "Internal business systems for Scottish organisations: staff portals, workflows, project tools, approvals, structured knowledge, and dashboards.", h1: "Internal business systems for Scottish organisations", eyebrow: "Operational software / Scotland", kind: "service",
    definition: "An internal business system gives staff one controlled place to manage a specific operation: enquiries, projects, records, approvals, documents, knowledge, handovers, or reporting. mccaigs designs and builds bespoke systems for Scottish organisations when spreadsheets, inboxes, and disconnected tools no longer support the work reliably.", price: "Priced following discovery.", cta: "Map an internal system",
    sections: [
      { heading: "Start with the operation that needs to work", paragraphs: ["The useful starting point is not a feature list. It is the real process: who does the work, what information they need, which decisions follow fixed rules, where exceptions occur, and who remains accountable. That map determines whether the answer is a focused internal application, a portal, an integration, or a simpler improvement to an existing tool.", "Typical systems can coordinate enquiries, client onboarding, project status, field records, approvals, events, documents, staff knowledge, reporting, and handovers across distributed Scottish teams."] },
      { heading: "Make status, ownership, and exceptions visible", paragraphs: ["A dependable system records what happened, who owns the next action, which source was used, and where an exception needs review. Permissions, validation, audit history, backups, and failure behaviour matter as much as the main screen.", "Ordinary software rules handle predictable decisions. AI may assist with a bounded task such as classification, extraction, retrieval, or drafting when the benefit and review process are clear. It is not added merely to label the system as AI-powered."] },
    ],
    approach: ["Observe the current workflow, users, records, and repeated effort.", "Define roles, permissions, rules, exceptions, integrations, and source ownership.", "Prototype the smallest end-to-end operational path.", "Build validation, status, handoffs, audit history, and recovery behaviour.", "Test, document, launch, and maintain the system."],
    deliverables: ["Operational and data model", "Staff or partner portal", "Workflow and project tools", "Permissions and approval controls", "Dashboard, reporting, and audit history", "Integration and operating documentation"],
    fit: ["Scottish SMEs outgrowing spreadsheets and inbox-led coordination", "Distributed teams that need visible status and consistent handovers", "Organisations with a distinctive process that generic software does not support well"],
    limitations: ["A standard product may be better when the process is common and requires little adaptation.", "Discovery must confirm access, migration quality, third-party APIs, security needs, and ongoing ownership before a build is promised."],
    proof: [{ href: "/systems", label: "Selected technical systems", text: "Examples of logic-first portals, operational software, structured records, and controlled workflows." }],
    related: [{ href: "/bespoke-software-development-scottish-smes", label: "Bespoke software for Scottish SMEs" }, { href: "/ai-automation-scotland", label: "AI-assisted workflow automation" }, { href: "/deterministic-assistants-scotland", label: "Controlled knowledge assistants" }, { href: "/business-automation-west-highlands", label: "West Highland business automation" }],
    reviewed, areas: scotland,
    faqs: [{ question: "What is an internal business system?", answer: "It is a private application or portal built around an organisation's operation, records, rules, permissions, handovers, and reporting." }, { question: "When is bespoke internal software justified?", answer: "It can be justified when a distinctive, important process is poorly served by existing products and the operational benefit supports the cost of ownership." }, { question: "Can it connect existing services?", answer: "Often, but feasibility depends on each service's API, permissions, reliability, data quality, terms, and cost. Discovery confirms this before integration is promised." }, noGuarantee],
  },
  {
    slug: "bespoke-software-development-scottish-smes", path: "/bespoke-software-development-scottish-smes", title: "Bespoke Software Development for Scottish SMEs", description: "Bespoke software development for Scottish SMEs, including portals, internal systems, workflow applications, structured platforms, and integrations.", h1: "Bespoke software development for Scottish SMEs", eyebrow: "Custom platforms / Scotland", kind: "service",
    definition: "Bespoke software is designed around a business process, user group, data model, or service that standard products cannot support well enough. mccaigs is an Edinburgh technical studio building maintainable web applications, portals, internal systems, workflow tools, and structured platforms for suitable SMEs across Scotland.", price: "Priced following discovery.", cta: "Discuss a bespoke software project",
    sections: [
      { heading: "Choose custom software for a real business reason", paragraphs: ["A bespoke build should solve a valuable constraint: repeated administration, disconnected customer journeys, a specialist operational process, difficult reporting, fragmented knowledge, or a digital service that differentiates the business. It should not recreate a mature standard product without a clear advantage.", "Discovery compares the custom route with configuration, integration, and off-the-shelf options. If a smaller intervention is more sensible, the technical recommendation should say so."] },
      { heading: "Build a complete service, not an isolated prototype", paragraphs: ["Production software needs usable interfaces, accessibility, permissions, validation, performance, security decisions, backups, error handling, observability, documentation, and an owner after launch. The architecture should match the SME's operating capacity rather than introduce unnecessary platforms and maintenance.", "mccaigs can deliver public web applications, customer or partner portals, staff tools, structured content and event systems, workflow software, dashboards, and carefully bounded AI features. Suitable projects can be delivered remotely across Scotland from Edinburgh."] },
    ],
    approach: ["Define the business constraint, users, value, and ownership.", "Compare bespoke, configured, integrated, and standard-product options.", "Model the data and prototype the smallest complete user journey.", "Build the application with permissions, validation, testing, and failure handling.", "Launch with documentation, handover, and an agreed maintenance route."],
    deliverables: ["Technical discovery and option assessment", "Application and data architecture", "Accessible web application or portal", "Internal workflow and reporting tools", "Third-party integrations where feasible", "Testing, deployment guidance, and operating documentation"],
    fit: ["Scottish SMEs with a distinctive and valuable operational process", "Businesses replacing fragile spreadsheets, inboxes, or disconnected tools", "Teams building a specialised digital service or customer platform"],
    limitations: ["Bespoke software carries ongoing ownership and maintenance responsibilities.", "Budget, schedule, migration, security, and integration commitments require discovery; this page does not provide a fixed project quote."],
    proof: [{ href: "/systems", label: "Selected systems", text: "Production examples showing the studio's approach to structured information, portals, workflows, and logic-first software." }, { href: "/studio", label: "About the technical studio", text: "How mccaigs approaches architecture, implementation, evidence, and long-term maintainability." }],
    related: [{ href: "/internal-business-systems-scotland", label: "Internal business systems" }, { href: "/custom-software-edinburgh", label: "Custom software in Edinburgh" }, { href: "/ai-systems-scotland", label: "Practical AI systems" }, { href: "/ai-automation-scotland", label: "AI automation for Scottish organisations" }],
    reviewed, areas: scotland,
    faqs: [{ question: "What bespoke software does mccaigs build?", answer: "Suitable work includes web applications, customer and staff portals, internal systems, workflow tools, structured platforms, dashboards, integrations, and bounded AI-assisted features." }, { question: "Does mccaigs work with SMEs outside Edinburgh?", answer: "Yes. mccaigs is based in Edinburgh and can deliver suitable projects remotely for SMEs throughout Scotland." }, { question: "How much does bespoke software cost?", answer: "It is priced following discovery because users, data, integrations, security, migration, and operating requirements materially change the scope." }, noGuarantee],
  },
  {
    slug: "ai-systems-west-highlands", path: "/ai-systems-west-highlands", title: "AI Systems West Highlands", description: "Practical AI and structured knowledge systems for West Highland tourism, hospitality, marine, events, and distributed organisations.", h1: "Practical AI systems for West Highland organisations", eyebrow: "Operational AI / West Highlands", kind: "service",
    definition: "mccaigs builds controlled assistants, structured knowledge, portals, internal tools, and bounded AI features for organisations in the West Highlands. The work is designed around seasonal demand, distributed teams, third-party platforms, and limited internal technical capacity.", price: "Priced following discovery.", cta: "Discuss a West Highland AI system",
    sections: [
      { heading: "Turn scattered local knowledge into an operational source", paragraphs: ["Visitor information, events, availability, transport dependencies, facilities, policies, and local guidance may live across staff knowledge, documents, calendars, websites, and booking platforms. A structured system defines which source owns each fact and how it reaches the people who need it.", "The same pattern can support accommodation, attractions, hospitality, yacht charter and sailing, food and drink, ferries and transport, rural services, and distributed organisations. The content model must follow the real operation rather than a generic tourism template."] },
      { heading: "Controlled assistance for practical questions", paragraphs: ["A deterministic assistant can answer approved questions about facilities, access, events, or service scope, then use a clear fallback when the source does not know. Generative features may help with summarisation or drafting where variability is acceptable.", "The independent McCaig's Tower project demonstrates the regional value of structured events, multilingual visitor content, local relationships, and controlled answers without claiming quantitative outcomes."] },
    ],
    approach: ["Identify users, recurring questions, and source owners.", "Model durable facts separately from changing records.", "Choose deterministic answers and bounded AI features.", "Build the public or internal interface with permissions and fallbacks.", "Test remote operation, handover, and maintenance."],
    deliverables: ["Structured visitor knowledge", "Deterministic customer assistant", "Event and venue systems", "Internal or partner portal", "Bounded AI-assisted features", "Source ownership and maintenance guide"],
    fit: ["West Highland tourism, marine, hospitality, and event organisations", "Distributed teams managing repeated questions and handovers", "Organisations with fragmented information and limited technical resources"],
    limitations: ["A system cannot make an unrelated third-party platform accurate or available.", "Safety, travel, access, and time-sensitive information need named source owners and review rules."],
    proof: [{ href: "/insights/mccaigs-tower-structured-visitor-system-case-study", label: "McCaig's Tower visitor system case study", text: "Regional production evidence for structured events, multilingual content, and deterministic assistance." }],
    related: [{ href: "/ai-systems-scotland", label: "AI systems across Scotland" }, { href: "/business-automation-west-highlands", label: "West Highland business automation" }, { href: "/ai-visibility-oban", label: "AI visibility in Oban" }],
    reviewed, areas: westHighlands,
    faqs: [{ question: "What AI systems suit West Highland organisations?", answer: "Useful examples include structured visitor knowledge, event and venue records, controlled assistants, enquiry workflows, internal portals, and bounded document or reporting tools." }, { question: "Can mccaigs work remotely with a West Highland team?", answer: "Yes. mccaigs is based in Edinburgh and can deliver suitable work remotely, with the operating team retaining ownership of approved facts and updates." }, { question: "Does every visitor assistant need generative AI?", answer: "No. Practical recurring questions are often better served by deterministic answers from approved knowledge with a clear fallback." }, noGuarantee],
  },
  {
    slug: "business-automation-west-highlands", path: "/business-automation-west-highlands", title: "Business Automation West Highlands", description: "Business automation for West Highland organisations, connecting enquiries, bookings, events, documents, approvals, and distributed team handovers.", h1: "Business automation for West Highland organisations", eyebrow: "Operational workflows / West Highlands", kind: "service",
    definition: "Business automation connects repeated work through reliable rules, data handoffs, notifications, approvals, and visible status. For West Highland organisations, that can reduce administration across seasonal enquiries, bookings, events, suppliers, documents, and distributed teams without adding unnecessary AI.", price: "Priced following discovery.", cta: "Map a West Highland workflow",
    sections: [
      { heading: "Reduce pressure when demand and staffing change", paragraphs: ["Seasonal demand can expose fragile processes. Enquiries arrive through several channels, availability sits in third-party systems, updates are repeated manually, and important context depends on one member of staff being available.", "A useful automation maps the existing process first. Fixed rules can validate a request, assign ownership, request missing information, update status, and prepare a handover. AI is optional and should be used only for an interpretive task that cannot be handled reliably by ordinary software."] },
      { heading: "Keep people responsible and information traceable", paragraphs: ["Automation should show what happened, which source was used, who approved an exception, and what the next action is. This matters for remote professional services, marine operations, hospitality, events, local retailers, trades, and organisations coordinating across sites.", "mccaigs builds within the tools and constraints that make operational sense. The result may be a focused internal application, a portal, or an integration around an existing booking or accounting platform."] },
    ],
    approach: ["Observe the current workflow and repeated effort.", "Define rules, data owners, exceptions, and permissions.", "Choose the smallest useful automation boundary.", "Build status, handoffs, notifications, and review controls.", "Test peak and failure scenarios before launch."],
    deliverables: ["Process and bottleneck map", "Enquiry and handover workflow", "Approval and notification rules", "Portal or internal dashboard", "Third-party integration where suitable", "Audit trail and operating documentation"],
    fit: ["Small teams managing seasonal enquiry or booking pressure", "Distributed organisations with repeated handovers", "Businesses relying on spreadsheets, inboxes, and disconnected tools"],
    limitations: ["Automation should not be used to conceal a broken process or unclear ownership.", "Third-party integrations depend on available APIs, permissions, service reliability, and commercial terms."],
    proof: [{ href: "/systems", label: "Selected technical systems", text: "Examples of the studio's logic-first approach to workflows, internal tools, and operational software." }],
    related: [{ href: "/ai-automation-scotland", label: "AI-assisted automation across Scotland" }, { href: "/ai-systems-west-highlands", label: "West Highland AI systems" }, { href: "/aeo-agency-oban", label: "AEO support for Oban organisations" }],
    reviewed, areas: westHighlands,
    faqs: [{ question: "What can a West Highland business automate?", answer: "Common candidates include enquiry routing, information collection, booking handoffs, event updates, document preparation, approvals, reminders, reporting, and internal status tracking." }, { question: "Is AI required for business automation?", answer: "No. Reliable rules are usually the right foundation. AI may be added for a bounded interpretive or drafting task where it provides clear value." }, { question: "Can automation connect third-party booking tools?", answer: "Sometimes. The answer depends on the platform's API, permissions, reliability, and terms. Discovery should confirm this before a solution is promised." }, noGuarantee],
  },
] as const satisfies readonly EdinburghPage[];

export const scotlandPageMap = Object.fromEntries(scotlandPages.map((page) => [page.slug, page])) as unknown as Record<ScotlandPageSlug, EdinburghPage>;
